package ui;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import model.Team;

// Panel that allows to remove the input
public class RemovePlayerActionListener implements ActionListener {
    private Team team;

    public RemovePlayerActionListener(Team team) {
        this.team = team;
    }

    // Requires: e is a valid action event, typically generated by a button click
    // Modifies: this.updateFrame
    // Effects: displays a form to enter player name; removes the player if the player exits, 
    // returns an error message when the player dne
    public void actionPerformed(ActionEvent e) {
        JFrame removePlayerFrame = new JFrame();
        removePlayerFrame.setSize(400, 300);
        removePlayerFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        removePlayerFrame.setLayout(new GridLayout(8, 2));

        removePlayerFrame.add(new JLabel("Name:"));
        JTextField nameField = new JTextField();
        removePlayerFrame.add(nameField);

        addSubmitButton(removePlayerFrame, nameField);

        addCancelButton(removePlayerFrame);

        removePlayerFrame.setVisible(true);

    }

    // EFFECTS: add submit button
    private void addSubmitButton(JFrame removePlayerFrame, JTextField nameField) {
        JButton submitButton = new JButton("Submit");
        submitButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String name = nameField.getText();

                if (team.containsName(name)) {
                    team.removePlayer(name);
                    JOptionPane.showMessageDialog(removePlayerFrame, "Player removed successfully!", "Success",
                            JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(removePlayerFrame, "Player does not exist", "Fail",
                            JOptionPane.INFORMATION_MESSAGE);
                }
                removePlayerFrame.dispose();
            }
        });
        removePlayerFrame.add(submitButton);

    }

    // EFFECTS: add cancel Button
    private void addCancelButton(JFrame removePlayerFrame) {
        JButton cancelButton = new JButton("Cancel");
        cancelButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                removePlayerFrame.dispose(); // Close the add player window
            }
        });
        removePlayerFrame.add(cancelButton);

    }

    

}
